/*1*/ USE universidad; SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = "alumno" ORDER BY apellido1 DESC, apellido2 DESC, nombre DESC;
/*2*/ SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = "alumno" AND telefono IS NULL;
/*3*/ SELECT * FROM persona WHERE tipo = "alumno" AND fecha_nacimiento LIKE "1999-%";
/*4*/ SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = "profesor" AND telefono IS NULL AND NIF LIKE "%K";
/*5*/ SELECT nombre FROM asignatura WHERE curso = 3 AND cuatrimestre = 1 AND id_grado = 7;
/*6*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor INNER JOIN departamento ON departamento.id = profesor.id_departamento ORDER BY apellido1, apellido2, persona.nombre ASC;
/*7*/ SELECT persona.NIF, asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE NIF = "26902806M";
/*8*/ SELECT DISTINCT departamento.nombre FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento INNER JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor INNER JOIN grado ON asignatura.id_grado = grado.id WHERE grado.nombre = "Grado en Ingeniería Informática (Plan 2015)";
/*9*/ SELECT DISTINCT persona.nombre, persona.apellido1, persona.apellido2 FROM persona INNER JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_alumno = persona.id INNER JOIN asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE curso_escolar.anyo_inicio = 2018 AND curso_escolar.anyo_fin = 2019;


/*1*/ USE universidad; SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id LEFT JOIN persona ON persona.id = profesor.id_profesor WHERE persona.tipo = "profesor" ORDER BY departamento.nombre, apellido1, apellido2, persona.nombre ASC;
/*2*/ SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id LEFT JOIN persona ON persona.id = profesor.id_profesor WHERE persona.tipo = "profesor" AND profesor.id_departamento IS NULL ORDER BY departamento.nombre, apellido1, apellido2, persona.nombre ASC;
/*3*/ SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM profesor RIGHT JOIN departamento ON profesor.id_departamento = departamento.id LEFT JOIN persona ON persona.id = profesor.id_profesor WHERE persona.tipo = "profesor" AND profesor.id_departamento IS NULL ORDER BY departamento.nombre, apellido1, apellido2, persona.nombre ASC;
/*4*/ SELECT DISTINCT persona.apellido1, persona.apellido2, persona.nombre FROM profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor LEFT JOIN persona ON persona.id = profesor.id_profesor WHERE asignatura.id_profesor IS NULL;
/*5*/ SELECT nombre FROM asignatura LEFT JOIN profesor ON asignatura.id_profesor = profesor.id_profesor WHERE profesor.id_profesor IS NULL;
/*6*/ SELECT DISTINCT departamento.nombre FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor LEFT JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_asignatura = asignatura.id LEFT JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE asignatura.id_profesor IS NULL;


/*1*/ USE universidad; SELECT DISTINCT COUNT(*) FROM persona WHERE tipo = "alumno";
/*2*/ SELECT DISTINCT COUNT(*) FROM persona WHERE tipo = "alumno" AND fecha_nacimiento LIKE "1999%";
/*3*/ SELECT DISTINCT departamento.nombre, COUNT(id_profesor) AS numero_profesores FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.id ORDER BY numero_profesores DESC;
/*4*/ SELECT departamento.nombre, COUNT(id_profesor) AS numero_profesores FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER BY numero_profesores DESC;
/*5*/ SELECT grado.nombre, COUNT(asignatura.nombre) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre ORDER BY numero_asignaturas DESC;
/*6*/ SELECT grado.nombre, COUNT(asignatura.nombre) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre HAVING numero_asignaturas > 40 ORDER BY numero_asignaturas DESC;
/*7*/ SELECT grado.nombre, asignatura.tipo, SUM(asignatura.creditos) AS numero_creditos FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre, asignatura.tipo ORDER BY grado.nombre, numero_creditos DESC;
/*8*/ SELECT DISTINCT curso_escolar.anyo_inicio, COUNT(id_alumno) AS numero_alumnos_matriculados_asignaturas FROM curso_escolar LEFT JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id GROUP BY id_curso_escolar, id_asignatura, anyo_inicio;
/*9*/ SELECT DISTINCT persona.id, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.id) AS numero_asignaturas FROM profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor LEFT JOIN persona ON profesor.id_profesor = persona.id GROUP BY profesor.id_profesor ORDER BY numero_asignaturas DESC;
/*10*/ SELECT * FROM persona WHERE fecha_nacimiento = (SELECT MAX(fecha_nacimiento) FROM persona WHERE tipo = "alumno");
/*11*/ SELECT persona.id, persona.nombre, persona.apellido1, persona.apellido2, departamento.nombre AS nombre_departamento, asignatura.id AS id_asignatura FROM profesor LEFT JOIN departamento ON departamento.id = profesor.id_departamento LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor LEFT JOIN persona ON persona.id = profesor.id_profesor WHERE asignatura.id IS NULL;